version: "3.7"

services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 8081:27017
    networks:
      - golang-docker-1.1.1-network
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    networks:
      - golang-docker-1.1.1-network
  golang-docker-1.1.1:
    container_name: golang-docker-1.1.1
    image: app-golang:1.1.1
    ports:
      - 8080:8080
    depends_on:
      - mongo
      - redis
    environment:
      - PORT=8080
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - golang-docker-1.1.1-network

networks:
  golang-docker-1.1.1-network:
    name : golang-docker-1.1.1-network